<<<<<<< HEAD

name: Claude Code (Issues only)
=======
name: Claude Code
>>>>>>> c7b3856baee19c6fe1f00054241d88c0e7d57791

on:
  issues:
    types: [opened, assigned]
  issue_comment:
    types: [created]
<<<<<<< HEAD

permissions:
  contents: read
  issues: write
  actions: read

jobs:
  claude:
    # Reagisce solo a issue e commenti su issue (non PR) che contengono '@claude'
    if: |
      (
        github.event_name == 'issues' &&
        (
          contains(github.event.issue.title, '@claude') ||
          contains(github.event.issue.body, '@claude')
        )
      )
      ||
      (
        github.event_name == 'issue_comment' &&
        contains(github.event.comment.body, '@claude') &&
        !github.event.issue.pull_request
      )
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Print event context
        run: |
          echo "event_name=${{ github.event_name }}"
          echo "repo=${{ github.repository }}"
          echo "actor=${{ github.actor }}"
          echo "is_issue_on_pr=$([ -n "${{ github.event.issue.pull_request.url || '' }}" ] && echo true || echo false)"
          echo "issue_number=${{ github.event.issue.number }}"

      - name: Verify secret presence
        run: |
          if [ -z "${{ secrets.ANTHROPIC_API_KEY }}" ]; then
            echo "❌ Secret ANTHROPIC_API_KEY non visibile in questo contesto."
            echo "   Possibili cause: permissions delle Actions 'Read-only' oppure secret non definito."
            exit 1
          else
            echo "✅ Secret ANTHROPIC_API_KEY visibile."
          fi

      - name: Run Claude Code
        uses: anthropics/claude-code-action@v1
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          # trigger_phrase: "/claude"
          # claude_args: |
          #   --model claude-3-sonnet-20240229
          #   --max-turns 10
          #   --allowedTools "Bash(npm run test:*),Bash(npm run lint:*)"
=======
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]

jobs:
  claude:
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@claude')) ||
      (github.event_name == 'issues' && (contains(github.event.issue.body, '@claude') || contains(github.event.issue.title, '@claude')))
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
      id-token: write
      actions: read # Required for Claude to read CI results on PRs
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 1

      - name: Run Claude Code
        id: claude
        uses: anthropics/claude-code-action@v1
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}

          # Optional: Customize the trigger phrase (default: @claude)
          # trigger_phrase: "/claude"

          # Optional: Trigger when specific user is assigned to an issue
          # assignee_trigger: "claude-bot"

          # Optional: Configure Claude's behavior with CLI arguments
          # claude_args: |
          #   --model claude-opus-4-1-20250805
          #   --max-turns 10
          #   --allowedTools "Bash(npm install),Bash(npm run build),Bash(npm run test:*),Bash(npm run lint:*)"
          #   --system-prompt "Follow our coding standards. Ensure all new code has tests. Use TypeScript for new files."

          # Optional: Advanced settings configuration
          # settings: |
          #   {
          #     "env": {
          #       "NODE_ENV": "test"
          #     }
          #   }
>>>>>>> c7b3856baee19c6fe1f00054241d88c0e7d57791
